### ISSUE TITLE
awesome_print wont work in Rails if ActiveRecord is not used

### ISSUE THREAD

**Issue by alexw668** [awesome-print/awesome_print#2] opened 2010-04-09 21:40 UTC
Hi Michael,

Like your awesome_print. It's truly awesome! We want to use it in our Rails app, but since we are not using ActiveRecord (it's not even loaded), when we run ap, it complains about missing constant ActiveRecord::Base. Here is the stack trace for this problem:

#<Class:0x61e14e8>: uninitialized constant AwesomePrintRails::ActiveRecord
	from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant'
	from C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in `const_missing'
	from C:/Ruby/lib/ruby/gems/1.8/gems/awesome_print-0.1.2/lib/ap/mixin/rails.rb:17:in `printable'
	from C:/Ruby/lib/ruby/gems/1.8/gems/awesome_print-0.1.2/lib/ap/awesome_print.rb:128:in `awesome'
	from C:/Ruby/lib/ruby/gems/1.8/gems/awesome_print-0.1.2/lib/ap/core_ext/kernel.rb:10:in `send'
	from C:/Ruby/lib/ruby/gems/1.8/gems/awesome_print-0.1.2/lib/ap/core_ext/kernel.rb:10:in `ai'
	from C:/Ruby/lib/ruby/gems/1.8/gems/awesome_print-0.1.2/lib/ap/core_ext/kernel.rb:15:in `ap'
	from (irb):12

We are running Rails 2.3.5 on Ruby 1.8.6 on Windows platform.

Do you think it's a bug and can be easily fixed?

Thanks,
Alex

**Comment by thedanielhanke** [comment] 2016-06-06 18:53
i`d rather like to use AP without beeing forced to use ActiveRecord.

**Comment by gerrywastaken** [comment] 2016-06-07 05:35
@thedanielhanke or @alexw668 How did you go about creating a Rails application which does not load AR?

**Comment by alexw668** [comment] 2016-06-07 20:15
@gerrywastaken We have apps that uses no-SQL database like MongoDB or Neo4j (a graph database) that don't deal with AR.

**Comment by gerrywastaken** [comment] 2016-06-09 05:26
@alexw668 I mean, what is the process you used to stop it from loading. As in which file did you modify and how, so I can test the issue accurately and not end up making bad assumptions about your setup.

**Comment by thedanielhanke** [comment] 2016-07-19 14:17
@gerrywastaken sorry for this short delay.

```
head config/application.rb -n 10
require File.expand_path('../boot', __FILE__)

require 'rails'
%w(
  action_controller
  action_view
  action_mailer
).each do |framework|
  begin
    require "#{framework}/railtie"
```

was all i needed to do.

**Comment by thedanielhanke** [comment] 2016-07-20 21:11
can be fixed like this:

```
    def cast_with_active_record(object, type)
      cast = cast_without_active_record(object, type)
      return cast if !defined?(::ActiveRecord)

      if object.is_a?(::ActiveRecord::Base)
```

should become

```
    def cast_with_active_record(object, type)
      cast = cast_without_active_record(object, type)
      return cast if !defined?(::ActiveRecord::Base)       #< -----------------

      if object.is_a?(::ActiveRecord::Base)
```

or even by `unless (defined?(::ActiveRecord) || defined?(::ActiveRecord::Base)`

**Comment by gerrywastaken** [comment] 2016-07-21 11:55
I'm not sure how this ended up closed. I haven't yet had a chance to look into it. Thanks for the info @thedanielhanke 👍

**Comment by gerrywastaken** [comment] 2016-07-21 14:34
Ok so the original bug was created a long time ago so tracking it back, the problem was originally here:
https://github.com/awesome-print/awesome_print/blob/0.1.3/lib/ap/mixin/rails.rb#L17

It then moved here:
https://github.com/awesome-print/awesome_print/blob/0.2.0/lib/ap/mixin/active_record.rb

This commit should have then fixed the issue reported by @alexw668:
https://github.com/awesome-print/awesome_print/commit/05265cb4e53b48199241fe8a26bd97a47e3541ea#diff-e567c486212ebaee39cf4091c38a4d84R17

Then in this commit the AcitveRecord::Base check was swapped for an ActiveRecord check:
https://github.com/awesome-print/awesome_print/commit/dfbebd488769738ac854adf37c930ad1d31bb94f#diff-e567c486212ebaee39cf4091c38a4d84L17

Now this should not have affected @alexw668 as for him ActiveRecord isn't defined at all, so I'm unclear how is he would still be hitting the original bug.

@thedanielhanke Your bug appears to be that ActiveRecord is somehow getting defined by something (before awesome print is loaded), but it doesn't create ActiveRecord::Base.

Your fix is good, but I don't think it's the same issue as was reported here. I suspect the issue reported here was fixed quite some time ago. @alexw668 can you confirm?

**Comment by thedanielhanke** [comment] 2016-07-21 16:07
ok i created a new empty project and yes - you are right.

the evil is `msgpack-rails` which messes around with stuff like
```
module ActiveRecord
  module Serialization
    include ActiveModel::Serializers::Msgpack
  end
end
```


i know that they fail, but i wonder if that "change" might help out - i guess there are many further bad written gems out there like msgpack-rails. 

however, from my side this can be marked as closed. Thank you, @gerrywastaken

**Comment by gerrywastaken** [comment] 2016-07-22 05:10
I'm just glad your issue was solved. I think it's a good change regardless and I suspect there will be others who are affected by this issue so I'll likely merge it in.

Cheers for investigating the root cause, I really appreciate that. 👍 

I suspect @alexw668 was the one who originally closed this, but can't be sure as Github isn't telling me. I'll leave this open for a three more days to give @alexw668 a chance to respond.

**Closed** 2016-07-28 15:07 UTC

**Comment by thedanielhanke** [comment] 2016-08-05 17:27
you are welcome + cheers for this gem ;)
